// Code generated by zek 0.1.23; DO NOT EDIT.
package fgdgmlschema

import "encoding/xml"

// GCP was generated automatically by zek 0.1.23. DO NOT EDIT.
type GCP struct {
	XMLName  xml.Name `xml:"GCP"`
	Text     string   `xml:",chardata"`
	ID       string   `xml:"id,attr"`
	Fid      string   `xml:"fid"`
	LfSpanFr struct {
		Text         string `xml:",chardata"`
		ID           string `xml:"id,attr"`
		TimePosition string `xml:"timePosition"`
	} `xml:"lfSpanFr"`
	DevDate struct {
		Text         string `xml:",chardata"`
		ID           string `xml:"id,attr"`
		TimePosition string `xml:"timePosition"`
	} `xml:"devDate"`
	OrgGILvl string `xml:"orgGILvl"`
	Vis      string `xml:"vis"`
	Pos      struct {
		Text  string `xml:",chardata"`
		Point struct {
			Text    string `xml:",chardata"`
			ID      string `xml:"id,attr"`
			SrsName string `xml:"srsName,attr"`
			Pos     string `xml:"pos"`
		} `xml:"Point"`
	} `xml:"pos"`
	OrgName  string `xml:"orgName"`
	Type     string `xml:"type"`
	GcpClass string `xml:"gcpClass"`
	GcpCode  string `xml:"gcpCode"`
	Name     string `xml:"name"`
	B        string `xml:"B"`
	L        string `xml:"L"`
	Alti     string `xml:"alti"`
	AltiAcc  string `xml:"altiAcc"`
}
