// Code generated by zek 0.1.23; DO NOT EDIT.
package fgdgmlschema

import "encoding/xml"

// WStrA was generated automatically by zek 0.1.23. DO NOT EDIT.
type WStrA struct {
	XMLName  xml.Name `xml:"WStrA"`
	Text     string   `xml:",chardata"`
	ID       string   `xml:"id,attr"`
	Fid      string   `xml:"fid"`
	LfSpanFr struct {
		Text         string `xml:",chardata"`
		ID           string `xml:"id,attr"`
		TimePosition string `xml:"timePosition"`
	} `xml:"lfSpanFr"`
	DevDate struct {
		Text         string `xml:",chardata"`
		ID           string `xml:"id,attr"`
		TimePosition string `xml:"timePosition"`
	} `xml:"devDate"`
	OrgGILvl string `xml:"orgGILvl"`
	Vis      string `xml:"vis"`
	Area     Area   `xml:"area"`
	Type string `xml:"type"`
}
